### ISSUE TITLE
Read property node doesn't fetch the value

### ISSUE THREAD

**Issue by Ahmed-farag36** [thingweb/node-red-contrib-web-of-things#21]
Hi, first of all thanks for this nice package
1. I have installed the node-red add-on in the webthings Gateway.
2. I have installed the node-red-contrib-web-of-things package from palette manager.
3. I have connected a read property node to debug node and fetch the thing which is on the same network by local IP.
**Observations:**
1. After selecting node-red from the webthings gateway sidebar, I got an error page unless I ran a dockerd command in a new terminal, it is fixed!!.
2. After deploying the flow (read node to a debug node) nothing appear on the node-red's debug sidebar.
3. I tried write property node but nothing happened either.
4. Any help should be appreciated and thanks.

**Comment by egekorkan** [comment]
@Ahmed-farag36 sorry for the late reply. This project was in hibernation and is now moved to https://github.com/eclipse-thingweb/node-red/tree/main/node-red-node-wot. I will close the issue since I think that you are trying to interact with webthings which does not provide standard compliant TDs (at least not when you opened this issue). When installing the new project locally (soon it will be available in package manager), I do not observe this behavior.
