### ISSUE TITLE
cant install package on node-red

### ISSUE THREAD

**Issue by ameerhazo** [thingweb/node-red-contrib-web-of-things#24]
I'm trying to use this package to play around with the WoT implementation on the node-red but ive been having problems installing this package on the node red. I used both version of node.js (16.x) and (14.x) and node-red version 2.0.4 and I cant get it installed to use as node-red nodes. Any help would be greatly appreciated. Thanks you.

**Comment by egekorkan** [comment]
Hi @ameerhazo , sorry for the late reply. This project was in hibernation. Please have a look at https://github.com/eclipse-thingweb/node-red/tree/main/node-red-node-wot . It will be available on palette manager soon but you can at least install locally and it works. Given that your issue is old and uses old node.js versions, I will close this issue. Please open it in the new repo if you can replicate the same issue.
